openfoam-env:
  compiler:
  - toolchain: gcc
    spec: gcc@12
  mpi:
    spec: cray-mpich
  unify: true
  specs:
  - openfoam@2212 +int64
  views:
    openfoam:
    develop:
      exclude: ['openfoam']
